# ===============================
# Database Connection (MySQL)
# ===============================
# ??????? your_db_name, root, ??????????? ???????????????
spring.datasource.url=jdbc:mysql://localhost:3307/sgm_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Settings
# ===============================
# ????????: 'update' ?????????? Hibernate ?????/?????????????? Class Entity ??????
spring.jpa.hibernate.ddl-auto=update

# ????????????? SQL ?? Console ???????????????? (????????????? Debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.auto_quote_keyword=true

# Error responses
server.error.include-message=always

# ===============================
# File Upload Configuration
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB